### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by asomers** [tbu-/hexdump#2]
This crate hasn't been touched for 8 years, and there are a few obvious problems:

- It depends on an outdated version of itertools and arrayvec.
- The published package on crates.io does not match the source code on Github.  It seems that at least one git commit never got pushed to Github.
- Its dev-dependency on quickcheck-macros is so old that it won't even compile with a modern toolchain
- Its dependency on `num` relies on unstable library features and will stop compiling with future toolchains.  See https://github.com/rust-lang/rust/issues/64266 .

Does the author ever intend to fix these problems?  If not, I suggest it's time to file a RUSTSEC issue for an abandoned crate and fork this one.

**Comment by tbu-** [comment]
Your issue seems quite hostile. Is it common to threaten crates with RUSTSEC issues? Does RUSTSEC know of its weaponization?

**Comment by asomers** [comment]
Sorry @tbu- , I didn't mean for it to come across that way.  But this isn't an uncommon use of RUSTSEC; that's why they have a whole category for "unmaintained".  BTW, do you intend to pick this crate up again?

**Comment by tbu-** [comment]
> BTW, do you intend to pick this crate up again?

I do intend to fix issues if they're reported. A crate not needing updates is a good thing, not a bad one.

> * It depends on an outdated version of itertools and arrayvec.

I assume that causes some problem for you? Can you describe why it's bad for you that it does that?

> * The published package on crates.io does not match the source code on Github.  It seems that at least one git commit never got pushed to Github.

Yea, that's bad. Fixed it yesterday.

> * Its dev-dependency on quickcheck-macros is so old that it won't even compile with a modern toolchain
> 
> * Its dependency on `num` relies on unstable library features and will stop compiling with future toolchains.  See

Those are just dev-dependencies and shouldn't impact users of the crate. It's still annoying for developers, so should get fixed.

**Comment by asomers** [comment]
> * It depends on an outdated version of itertools and arrayvec

It means that downstream projects which already depend on one or both of those crates may end up building two versions, increasing build times and binary sizes.

**Comment by tbu-** [comment]
I removed the `itertools` and `num` dependency and upgraded the `quickcheck` dependency. The only thing remaining is `arrayvec`, which is not completely trivial: #3.
